# NumPy 


- Biblioteca de Algera Linear, a maioria das bibliotecas do Ecosistema PyData dependem de Numpy para rodarem.
- Construído em C, ou seja, roda mais rápido.

## Instalação

Anaconda:
conda install numpy

Pip:
pip install numpy

## Usando Numpy

In [1]:
import numpy as np

# Matrizes e arrays

## Numpy Arrays

Arrays são vetores 1D, e matrizes são vetores 2D

## Criando NumPy Arrays de uma lista

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Gera Arrays de 0s e 1s

In [8]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [9]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
#comenta

"""Documentation
Paramettros
"""


np.ones(3)

array([ 1.,  1.,  1.])

In [11]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Retorna elementos em um intervalo especificado

In [12]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [17]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Matriz identidade

In [14]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

### rand
Cria arrays gerados aleatoriamente no intervalo entre ``[0, 1)``.

In [18]:
np.random.rand(2)

array([ 0.74567252,  0.96999425])

In [19]:
np.random.rand(5,5)

array([[ 0.5253465 ,  0.36884187,  0.14898807,  0.09835   ,  0.63647067],
       [ 0.26600916,  0.21905087,  0.60965837,  0.37918533,  0.92242763],
       [ 0.41708373,  0.94450259,  0.97243775,  0.86899225,  0.09106906],
       [ 0.0346269 ,  0.90842582,  0.61181082,  0.37562209,  0.57687192],
       [ 0.64839676,  0.4167989 ,  0.77959074,  0.74253849,  0.3414703 ]])

### randn

Retorna arrays distribuidos aleatoriamente por Standard Normalization

In [20]:
np.random.randn(2)

array([-0.26243609,  1.35663689])

In [21]:
np.random.randn(5,5)

array([[-0.60080843, -2.25638942,  1.30525175,  0.26545391,  0.11233938],
       [-0.22954457, -0.69895677,  1.08886927,  1.91074888, -1.98268195],
       [-0.64216931, -0.4161804 , -0.19207334, -0.81998526, -0.11126852],
       [ 1.54072893,  0.19858718,  1.85175544, -0.63803629,  0.35483843],
       [-0.11201119,  0.64404011, -0.91801797,  0.35597406, -1.59334359]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).
Retorna inteiros aleatorios entre o intervalo especificado

In [22]:
np.random.randint(1,100)

10

In [23]:
np.random.randint(1,100,10)

array([77, 92, 79, 77, 25, 19, 93, 75, 21, 54])

## Atributos e Métodos de arrays

In [38]:
np.random.seed(3)
arr = np.arange(26)
ranarr = np.random.randint(0,50,10)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [40]:
ranarr

array([42, 24,  3,  8,  0, 21, 19, 10, 43, 41])

## Reshape
Retorna um array rearranjado

In [30]:
arr.reshape(5,5)

ValueError: cannot reshape array of size 26 into shape (5,5)

### max,min,argmax,argmin


In [31]:
ranarr

array([42,  0, 22, 37, 20, 21, 11, 11, 31, 47])

In [32]:
ranarr.max()

47

In [33]:
ranarr.argmax()

9

In [34]:
ranarr.min()

0

In [35]:
ranarr.argmin()

1

## Shape

Atributo para retornar a dimensão do array

In [ ]:
# Vector
arr.shape

In [ ]:
arr.reshape(1,25)

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)

In [ ]:
arr.reshape(25,1).shape

### dtype

Checando o tipo do objeto

In [ ]:
arr.dtype

# Great Job!