# NumPy 


- Biblioteca de Algera Linear, a maioria das bibliotecas do Ecosistema PyData dependem de Numpy para rodarem.
- Construído em C, ou seja, é otimizado para todar mais rápido.

## Instalação

Anaconda:
conda install numpy

Pip:
pip install numpy

## Usando Numpy

In [3]:
import numpy as np

# Matrizes e arrays

## Numpy Arrays

Arrays são vetores 1D, e matrizes são vetores 2D

## Criando NumPy Arrays de uma lista

In [1]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos Built-in 

### arange

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros e ones

Gera Arrays de 0s e 1s

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Retorna elementos em um intervalo especificado

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Matriz identidade

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

### rand
Cria arrays gerados aleatoriamente no intervalo entre ``[0, 1)``.

In [16]:
np.random.rand(2)

array([0.07767294, 0.27672468])

In [17]:
np.random.rand(5,5)

array([[0.96287977, 0.4805486 , 0.29759002, 0.87200672, 0.06364999],
       [0.37146409, 0.57737088, 0.83115669, 0.02363353, 0.15731322],
       [0.3603117 , 0.24360364, 0.80155677, 0.5382783 , 0.06229233],
       [0.44577206, 0.16790659, 0.00281972, 0.59399298, 0.9653379 ],
       [0.31493442, 0.86121326, 0.99944695, 0.82003646, 0.76625191]])

### randn

Retorna arrays distribuidos aleatoriamente por Standard Normalization

In [18]:
np.random.randn(2)

array([-1.27054276,  1.55223792])

In [19]:
np.random.randn(5,5)

array([[ 0.15006442,  0.85640675,  0.31928014, -0.55104985, -0.76218106],
       [ 0.5090997 ,  0.84302583,  0.17217334, -0.38943112, -0.98352661],
       [ 2.525678  ,  0.4911174 ,  0.27374809, -0.21462115, -0.07614348],
       [-0.51772698,  1.66066576,  1.16792208, -0.01855038,  2.65862867],
       [-0.42975137,  1.65725955, -0.84148899, -0.17954575, -1.33644009]])

### randint

Retorna aleatoriamente integers no intervalo (a, b), incluindo a, excluindo b.

In [20]:
np.random.randint(1,100)

71

In [21]:
np.random.randint(1,100,10)

array([ 8, 40, 36, 91,  9, 16, 67, 40, 40, 97])

## Atributos e Métodos de arrays

In [33]:
np.random.seed(3)
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr

array([42, 24,  3,  8,  0, 21, 19, 10, 43, 41])

## Reshape
Retorna um array rearranjado

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin


In [37]:
ranarr

array([42, 24,  3,  8,  0, 21, 19, 10, 43, 41])

In [38]:
ranarr.max()

43

In [39]:
ranarr.argmax()

8

In [40]:
ranarr.min()

0

In [41]:
ranarr.argmin()

4

## Shape

Atributo para retornar a dimensão do array

In [42]:
# Vector
arr.shape

(25,)

In [43]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [44]:
arr.reshape(1,25).shape

(1, 25)

In [45]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [46]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Checando o tipo do objeto

In [47]:
arr.dtype

dtype('int64')